Add Architecure section
artipie/white-paper pull request #2
Opened 2020-01-16 14:19 UTC by Sammers21

2020-01-16 14:58 UTC, yegor256 commented
@g4s8 please take a look

2020-01-17 13:36 UTC, g4s8 requested changes
@Sammers21 please check few comments

2020-01-17 13:36 UTC, g4s8 commented on wp.tex
> +	name: my-repo
@Sammers21 if we use repo name as file name, this field is not needed

2020-01-17 13:36 UTC, g4s8 commented on wp.tex
> +Engine store repository configuration in a .yml file. An example:
@Sammers21 I don't think yaml format is suitable here. Yaml is good for human-readable configuration files, but here we use repo files as a data storage for the service. The requirements for this format are fast data access & query, easy to modify from code. Human readability is also relevant, but it's not the most important criteria here. I'd use xml here, because it fits all requirements.

2020-01-22 12:23 UTC, Sammers21 commented on wp.tex
> +Engine store repository configuration in a .yml file. An example:
> The requirements for this format are fast data access & query
The configuration file modifications are occasional and rare, it happens a few times a day in the best case.

2020-01-22 12:25 UTC, Sammers21 commented on wp.tex
> +Engine store repository configuration in a .yml file. An example:
> easy to modify from code

Do you find it a non-trivial task to modify a .yml file from code?

2020-01-22 12:25 UTC, Sammers21 commented on wp.tex
> +	name: my-repo
Agree

2020-01-22 12:50 UTC, g4s8 approved these changes
@yegor256 please read it before merge

2020-01-22 13:06 UTC, merged